### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by azriel-stephen** [MemoonaTahira/MLZoomcamp2022#5]
Hello Memoona,
I liked the way you've structured your notes and specially the visual notes like the one below. Could you tell me what/how you've created these? It'll be really helpful. 
Thank you
![image](https://user-images.githubusercontent.com/85186840/204296775-8193c6a7-4fd0-428e-8333-6f31ad62fc47.png)

**Comment by MemoonaTahira** [comment]
Hello Azriel, thank you for appreciating. I use excalidraw to create these. https://excalidraw.com/ The file for this is attached below. You can unzip it and open it with excalidraw. I hope it can help you get started.


[week-5-Windows_WSL.zip](https://github.com/MemoonaTahira/MLZoomcamp2022/files/10104487/week-5-Windows_WSL.zip)

**Comment by azriel-stephen** [comment]
Thanks a lot Memoona for the quick reply. Excalidraw looks really interesting. I'll give it a try.
